### ISSUE TITLE
Feature Request: .shame functionality

### ISSUE THREAD

**Issue by sugitime** [R4stl1n/halgnu#1]
The .shame functionality should take one input:
.shame <User in which to shame>

The .shame functionality should then produce a random insult to said user.

For instance:
<Sugi> .shame r4stl1n
<HalGNU> You should be ashamed of your self and your family, r4stl1n.

Ideally, a list of insults would exist with a %user% token within the location where the users name should be present:

"You're an awful human being and deserve aids, %user%"
"Jesus Christ, %user%. I didn't know anyone could be that dumb."
"Go kill yourself, %user%"

In no instance should the %user% variable exist as the first word, as this presents the ability to inject commands.

**Comment by R4stl1n** [comment]
Implemented.
