### ISSUE TITLE
Feature Request: .lastseen Function

### ISSUE THREAD

**Issue by sugitime** [R4stl1n/halgnu#2]
The function .lastseen can be used to find the last time a member sent a message in chat, and the last thing the user said.

<User> .lastseen r4stl1n
<HalGNU> Last seen r4stl1n at 4:32pm "brb guys, going to suck a dick."

This will give other users insight into why a member is not presently responding. In the example above, r4stl1n noted that he is currently performing felatio and is unavailable.

**Comment by R4stl1n** [comment]
Im so glad potential employers see these tickets.

**Comment by R4stl1n** [comment]
Done.
