### ISSUE TITLE
Feature Request: .tell Functionality

### ISSUE THREAD

**Issue by sugitime** [R4stl1n/halgnu#3]
The .tell functionality should be used to allow a user to leave a message for another user who is currently not present.

<User> .tell User2 "r4stl1n is giving away free blowjobs!"
<HalGNU> User2 will receive the message when he comes online.

This will allow User to inform User2 that r4stl1n is currently offering oral sex at no cost. This could prove to be valuable information.

**Comment by R4stl1n** [comment]
implemented
